### ISSUE TITLE
[Dappbot Free Tier] - Update Stripe plans to reflect new signup on free tier - Types

### ISSUE THREAD

**Issue by eximchain137** [Eximchain/dappbot-types#8]
The stripe plans are inferred from dappbot types package where the change should happen:

https://github.com/Eximchain/dappbot-types/blob/9800fb4f7816bb1de0cce8088339be6fbae9ab9c/spec/methods/payment/payment.ts#L14

The arguments are also used in the following places, once the change is made test and make sure nothing is broken.

The DappBotAPI Repo uses stripe plans to create trials in two places:
 https://github.com/Eximchain/payment-gateway-stripe-lambda/blob/b78278fa89a5c8428f08b1b27de5b67a84187b4a/src/api.ts#L38

https://github.com/Eximchain/payment-gateway-stripe-lambda/blob/master/src/services/stripe.ts#L26

**Comment by john-osullivan** [comment]
This issue is now resolved, the interface and sample have both been upgraded.
